version: "3.8"
services:
  backend:
    env_file: .dev.env
    container_name: backend
    build:
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
  db:
    container_name: db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
  adminer_db:
    container_name: db-ui
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
